
esegui: 
	./main 3 5 -2 0.00001 
compila: Esercizio7_2.cpp FunzioneBase.h Parabola.h Solutore.h Bisezione.h funzioni.h
	g++ -o main Esercizio7_2.cpp FunzioneBase.h Parabola.h Solutore.h Bisezione.h funzioni.h

clean:
	rm main
